Repository CVSU-BSIT-2B/Project-Management-System-, pull requests merged in 2025-06, with the labels that each got.

#1 Master
  signin.php
Labels: enhancement

#2 Adding completed signin page
  signinpage/bg.png
  signinpage/calendar.png
  signinpage/consign.php
  signinpage/logo.png
  signinpage/proj.png
  signinpage/signin.css
  signinpage/student.png
Labels: enhancement

#6 Merging file issue
  Homepage/homepage.css
  Homepage/homepage.php
  Homepage/projhomepage.css
  Homepage/projhomepage.php
  loginpage/bg.png
  loginpage/calendar.png
  loginpage/conlog.php
  loginpage/login.css
  loginpage/login.php
  loginpage/logo.png
  loginpage/proj.png
  loginpage/student.png
  signinpage/bg.png
  signinpage/calendar.png
  signinpage/consign.php
  signinpage/logo.png
  signinpage/proj.png
  signinpage/signin.css
  signinpage/signin.php
  signinpage/student.png
Labels: bug

#8 Re-pushing signinpage folder
  signinpage/bg.png
  signinpage/calendar.png
  signinpage/consign.php
  signinpage/logo.png
  signinpage/proj.png
  signinpage/signin.css
  signinpage/signin.php
  signinpage/student.png
Labels: bug, duplicate

#10 Create Project
  create_project/create.css
  create_project/create.html
  create_project/create.php
  create_project/logo.png
Labels: enhancement

#12 Adding task and link folder
  input-join/input.css
  input-join/input.php
  input-join/join.css
  input-join/join.php
  task-link/link.css
  task-link/link.js
  task-link/link.php
  task-link/tasks.css
  task-link/tasks.php
Labels: enhancement, Assignment
